#!/bin/bash
if [ -z $1 ]; then
	echo -e "\nYou must provide a target!\nTargets: tgl, generic\n"
	exit 1
fi

if [ ! -z $2 ] && [ "$2" != "native" ]; then
	echo -e "invalid argument!\nvalid args: native\n"
	exit 1
fi

pkgnameb=""
pkgnamel=""
optflag=""
cmd=""

if [ -f "customization.cfg" ]; then
	rm customization.cfg
fi

if [ "$1" == "pull" ]; then
	git restore customization.cfg
	git pull
	exit 0
fi

case "$1" in
	"tgl")
		cmd="mitigations=off nowatchdog i915.enable_guc=2"
		;;
	"generic")
		cmd="mitigations=off nowatchdog"
		;;
	"sandy");;
	*)
		echo -e "unknown target!\n"
		exit 1
		;;
esac

case "$1" in
	"tgl")
		pkgnamel="awx-tgl"
		pkgnameb="$pkgnamel-tkg"
		optflag="tigerlake"
		;;
	"generic")
		pkgnamel="generic4"
		pkgnameb="tkg-$pkgnamel"
		optflag="generic_v4"
		;;
	"sandy")
		pkgnamel="linux"
		pkgnameb="$pkgnamel-tkg"
		;;
	*)
		echo -e "unknown target!\n"
		exit 1
		;;
esac

if [ ! -z $2 ]; then
	case "$1" in
		"tgl"|"sandy")
			optflag="native_intel"
			;;
		"generic") ;;
		*)
			echo -e "unknown target!\n"
			exit 1
			;;
	esac
fi

cp tkgconfigbase.cfg customization.cfg
sed -i "s/PKGNAMEB/$pkgnameb/" customization.cfg
sed -i "s/PKGNAMEL/$pkgnamel/" customization.cfg
sed -i "s/OPTFLAG/$optflag/" customization.cfg
sed -i "s/CMDARGS/$cmd/" customization.cfg

makepkg -s