#!/bin/bash
if [ -z $1 ]; then
	echo -e "You must provide a target!\nTargets: tgl\n"
	exit 1
fi

if [ ! -z $2 ] && [ "$2" != "native" ]; then
	echo -e "invalid argument!\nvalid args: native\n"
	exit 1
fi

pkgname=""
drid=""
galliumd=""
vulkand=""
flags=""
commit=""
prs="18402 18725 18880"

ccache -C

sudo rm -r pkg src

if [ -f "customization.cfg" ]; then
	rm customization.cfg
fi

if [ "$1" == "pull" ]; then
	git restore customization.cfg
	git restore PKGBUILD
	git pull
	exit 0
fi

case "$1" in
	"tgl")
		galliumd="svga,virgl,swrast,iris"
		vulkand="intel"
		;;
	"amd")
		galliumd="radeonsi,swrast,svga,virgl"
		vulkand="amd"

		sed -i 's/$_layers/-D vulkan-layers=device-select,overlay/' PKGBUILD
		;;
	*)
		echo -e "unknown target!\n"
		exit 1
		;;
esac

case "$1" in
	"tgl")
		flags="-march=tigerlake -mtune=tigerlake"
		pkgname="mesa-tgl-tkg"
		;;
	*)
		echo -e "unknown target!\n"
		exit 1
		;;
esac

if [ ! -z $2 ]; then
	flags="-mtune=native"
else
	sudo sed -i "s/-mtune=native/$flags/" /etc/makepkg.conf
fi

git restore PKGBUILD
cp tkgconfigbase.cfg customization.cfg
sed -i "s/DRIDRVS/$drid/" customization.cfg
sed -i "s/GALLIUMDRVS/$galliumd/" customization.cfg
sed -i "s/VULKANDRVS/$vulkand/" customization.cfg
sed -i "s/OPTFLAGS/$flags/" customization.cfg
sed -i "s/MESACOMMIT/$commit/" customization.cfg
sed -i "s/MESAPRS/$prs/" customization.cfg
sed -i "s/mesa-tkg/$pkgname/g" PKGBUILD

makepkg -s